// Error actions
export const GET_ERRORS = "GET_ERRORS";
export const RESET_ERRORS = "RESET_ERRORS";

// Auth
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER = "SET_USER";

// Assets
export const LOAD_ASSETS_REQUEST = "LOAD_ASSETS_REQUEST";
export const LOAD_ASSETS_SUCCESS = "LOAD_ASSETS_SUCCESS";
export const LOAD_ASSETS_FAILURE = "LOAD_ASSETS_FAILURE";
export const LOAD_CURRENT_ASSET_REQUEST = "LOAD_CURRENT_ASSET_REQUEST";
export const LOAD_CURRENT_ASSET_SUCCESS = "LOAD_CURRENT_ASSET_SUCCESS";
export const LOAD_CURRENT_ASSET_FAILURE = "LOAD_CURRENT_ASSET_FAILURE";
export const DELETE_CURRENT_ASSET = "DELETE_CURRENT_ASSET";
export const CREATE_NEW_ASSET_REQUEST = "CREATE_NEW_ASSET_REQUEST";
export const CREATE_NEW_ASSET_SUCCESS = "CREATE_NEW_ASSET_SUCCESS";
export const CREATE_NEW_ASSET_FAILURE = "CREATE_NEW_ASSET_FAILURE";
export const MODIFY_ASSET_REQUEST = "MODIFY_ASSET_REQUEST";
export const MODIFY_ASSET_SUCCESS = "MODIFY_ASSET_SUCCESS";
export const MODIFY_ASSET_FAILURE = "MODIFY_ASSET_FAILURE";

// Locations
export const LOAD_LAST_LOCATION_REQUEST = "LOAD_LAST_LOCATION_REQUEST";
export const LOAD_LAST_LOCATION_SUCCESS = "LOAD_LAST_LOCATION_SUCCESS";
export const LOAD_LAST_LOCATION_FAILURE = "LOAD_LAST_LOCATION_FAILURE";
export const LOAD_ALL_LOCATIONS_REQUEST = "LOAD_ALL_LOCATIONS_REQUEST";
export const LOAD_ALL_LOCATIONS_SUCCESS = "LOAD_ALL_LOCATIONS_SUCCESS";
export const LOAD_ALL_LOCATIONS_FAILURE = "LOAD_ALL_LOCATIONS_FAILURE";
export const DELETE_LAST_LOCATION = "DELETE_LAST_LOCATION";
export const DELETE_ALL_LOCATIONS = "DELETE_LAST_LOCATION";

// Notifications
export const SET_NOTIFICATION = "SET_NOTIFICATION";

// Projects
export const LOAD_ALL_PROJECTS_REQUEST = "LOAD_ALL_PROJECTS_REQUEST";
export const LOAD_ALL_PROJECTS_SUCCESS = "LOAD_ALL_PROJECTS_SUCCESS";
export const LOAD_ALL_PROJECTS_FAILURE = "LOAD_ALL_PROJECTS_FAILURE";
// TODO: finish this
